name: Deploy to Digital Ocean

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: smallbets/campfire

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: push_to_registry
    name: Deploy to Droplet
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Execute SSH commands
        run: |
          sshpass -p ${{ secrets.DROPLET_PASSWORD }} ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} "
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} &&
            docker pull smallbets/campfire:${{ github.ref_name }} &&
            docker stop campfire || true &&
            docker rm campfire || true &&
            docker run \
              --name campfire \
              --restart unless-stopped \
              -p 80:80 \
              -p 443:443 \
              -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
              -e AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} \
              -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
              -e GUMROAD_ON=${{ secrets.GUMROAD_ON }} \
              -e GUMROAD_ACCESS_TOKEN=${{ secrets.GUMROAD_ACCESS_TOKEN }} \
              -e GUMROAD_PRODUCT_ID=${{ secrets.GUMROAD_PRODUCT_ID }} \
              -e WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }} \
              -e SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} \
              -e VAPID_PRIVATE_KEY=${{ secrets.VAPID_PRIVATE_KEY }} \
              -e VAPID_PUBLIC_KEY=${{ secrets.VAPID_PUBLIC_KEY }} \
              -e TLS_DOMAIN=${{ secrets.DOMAIN }} \
              -e APP_VERSION=${{ github.sha }} \
              -v /disk/campfire/:/rails/storage/ \
              -d smallbets/campfire:${{ github.ref_name }}"
        env:
          SSH_PASSWORD: ${{ secrets.DROPLET_PASSWORD }}
